[package]
repo = "neovim/neovim"
basename = "neovim"
description = "Neovim is a project that seeks to aggressively refactor Vim in order to:"

[download]
filename = "nvim-linux-\$TARGET_ARCH.appimage"
url_template = "https://github.com/\{repo}/releases/download/\{version}/\{filename}"
extract_cmd = ""

[[install_files]]
source = "\$DOWNLOAD_FILENAME"
permissions = "755"
dest = "/usr/bin/nvim"
